---
editor_options: 
  chunk_output_type: console
params:
  con: NULL
  schema: NULL
  tbl: NULL
  title: 'My report title' # i.e. report_title
  report_text: NULL
  plot_distinct: TRUE
  plot_type: 'lollipop'
  plot_limit: 40L
  plot_limit_text: 20L
  out: TRUE
  col: NULL
  entry: NULL
  output_dir: NULL # https://community.rstudio.com/t/is-it-possible-to-save-the-html-output-in-a-directory-which-is-not-the-one-where-the-rmd-file-resides/3588/6
  output_file: 'report'
  file: TRUE
  file_format: 'csv'
  file_type: 'json'
  verbose: FALSE
title: "`r params$title`"
date: "`r format(Sys.Date(), '%d.%m.%Y')`"
---

```{r data, echo=FALSE, message=FALSE, warning=FALSE}
tbl_l = fetch(con = con,
              schema = schema,
              tbl = tbl,
              col = col,
              entry = entry,
              verbose = verbose)
meta_dt = meta(con = con,
               schema = schema,
               tbl = tbl,
               plot_type = plot_type,
               plot_limit = plot_limit,
               plot_limit_text = plot_limit_text,
               output_dir = output_dir,
               output_file = output_file)
```

```{r text, echo=FALSE, results='asis'}
if (!is.null(report_text)) {
  if (file.exists(report_text)) {
    readLines(report_text)
  } else {
    cat(report_text)
  }
}
```

## Meta table
```{r meta, echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(meta_dt)
```

## Summary table
```{r table, echo=FALSE, message=FALSE, warning=FALSE}
summary_dt = tbl_l$summary
idx = grep('^distinct$|n_', names(summary_dt), value = TRUE)
n_row = meta_dt[ variable == 'table rows', as.numeric(value) ]
summary_dt[ ,
            (idx) := lapply(.SD, function(x) perc_value(x, n_row)),
            .SDcols = idx ]

knitr::kable(summary_dt)
```

## Column plots
```{r plot, echo=FALSE, fig.height=7, fig.width=15, dpi=72, message=FALSE, warning=FALSE, results='asis'}
if (plot_distinct) {
  for (i in seq_along(tbl_l$distinct)) {
    dat = tbl_l$distinct[[i]]
    col = names(tbl_l$distinct)[i]
    setDT(dat)
    dat[ , var20 := as.character(str_limit(get(col), plot_limit_text)) ]
    dat[ , n_distinct := as.numeric(n_distinct) ] # NB to get rid of integer64, that might be returned - can be done more gracefully - as.integer doesn't work!
    if (!is.null(plot_limit) & plot_limit < nrow(dat)) {
      dat = dat[ 1:plot_limit ]
    }
    height = ceiling(length(unique(dat$var20)) / 4)
    # header
    cat('  \n###', col, '\n') # OPTION pander::pandoc.header(paste0('Column: ', col), level = 3)
    # plots
    # TODO add if statement numeric vs caharacter/factor here
    # TODO then plot numeric variables as violins with quantiles
    if (plot_type == 'lollipop') {
      subchunkify(
        print(pl_lollipop(dat = dat, x = 'var20', y = 'n_distinct')),
        fig.height = height, fig.width = 15,
        chunk_name = paste0('plot-', i)
      )
    }
    if (plot_type == 'bar_horiz') {
      print(pl_bar_horiz(dat = dat, x = 'var20', y = 'n_distinct'))
    }
    if (plot_type == 'treemap') {
      print(pl_treemap(dat = dat, x = 'var20', y = 'n_distinct'))
    }
    # OLD print(pl_gg(dat = dat, x = 'var20', y = 'n_distinct', plot_type = plot_type))
    cat('<a href="#top">Back to top</a>')
    cat('  \n') # OPTION # pander::pandoc.p(''); pander::pandoc.p('')
  }
} else {
  print('Plots should not be printed.')
}

```

```{r write, echo=FALSE, message=FALSE, warning=FALSE}
if (is.null(file)) {
  print('Files should not be written.')
} else {
  write_to_dir(l = tbl_l$distinct,
               output_dir = output_dir,
               output_file = output_file,
               file_format = file_format,
               file_type = file_type)
}
```
